spring.application.name=CalculadoraIR
spring.datasource.url=jdbc:postgresql://localhost:5432/calculadora_ir
spring.datasource.username=postgres
spring.datasource.password=250780

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true